name: Deploy Documentation to GitHub Pages

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    env:
      docs-directory: ./docs
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install DocFx
      shell: pwsh
      run: choco install docfx -y
    - name: Generate Metadata
      shell: pwsh
      run: docfx metadata
      working-directory: ${{env.docs-directory}}
    - name: Build Docs
      shell: pwsh
      run: docfx build
      working-directory: ${{env.docs-directory}}
    - name: Push Docs
      run: |
        cd ..
        echo Cloning Repo
        git clone -b gh-pages https://github.com/kenswan/blazor-focused.git gh-pages
        echo Setting Global Creds
        git config --global user.name 'Automated Push'
        git config --global user.email 'kenswan@users.noreply.github.com'
        echo Set Remote
        cd gh-pages
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        echo Checkout gh-pages
        git checkout gh-pages
        echo Copy Files
        cd ..
        mv blazor-focused/docs/_site gh-pages/docs
        cd gh-pages
        echo Add/Commit Files
        git add -A
        git commit -m "Updating Site"
        echo Push Files
        git push
