name: Deploy Documentation to GitHub Pages

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    env:
      docs-directory: ./docs
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install DocFx
      shell: pwsh
      run: choco install docfx -y
    - name: Generate Metadata
      shell: pwsh
      run: docfx metadata
      working-directory: ${{env.docs-directory}}
    - name: Build Docs
      shell: pwsh
      run: docfx build
      working-directory: ${{env.docs-directory}}
    - name: Push Docs
      run: |
        cd ..
        git clone -b gh-pages https://github.com/kenswan/blazor-focused.git gh-pages
        mv blazor-focused/docs/_site gh-pages/docs
        cd gh-pages
        git add -A
        git commit -m "Updating Site"
        git push
