name: Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  deploy-gh-pages:

    runs-on: windows-latest
    env:
      docs-directory: ./docs
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install DocFx
      shell: pwsh
      run: choco install docfx -y
    - name: Generate Metadata
      shell: pwsh
      run: docfx metadata
      working-directory: ${{env.docs-directory}}
    - name: Build Docs
      shell: pwsh
      run: docfx build
      working-directory: ${{env.docs-directory}}
    - name: Prepare GitHub Pages Repo
      run: |
        cd ..
        git clone -b gh-pages https://github.com/BlazorFocused/BlazorFocused.git gh-pages
        git config --global user.name 'Automated'
        git config --global user.email 'kenswan@users.noreply.github.com'
        cd gh-pages
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    - name: Copy & Push Doc Files
      run: |
        cd ..
        rm -r gh-pages/docs
        mv blazorfocused/docs/_site gh-pages/docs
        cd gh-pages
        git add -A
        git commit -m "Commit #${{ github.sha }}"
        git push
